<?php

namespace Database\Seeders;

use App\Models\Enquiry;
use Illuminate\Database\Seeder;

class EnquirySeeder extends Seeder
{
    public function run(): void
    {
        Enquiry::truncate();

        $now = now();

        $rows = [
            ['date' => '2026-01-27', 'name' => 'Phillip Dieu',           'phone' => '0401 440 571', 'email' => 'phillip.dieu@gmail.com',          'source' => 'Email',             'lead' => 'Google',            'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 209 Hydrus St, Austral',               'fu' => '',                                                            'fct_offset' => 30],
            ['date' => '2026-03-27', 'name' => 'Srinivas Mallacheruvu',  'phone' => '0415 799 903', 'email' => 'mallacheruvus@yahoo.co.nz',        'source' => 'Email',             'lead' => 'Facebook',          'type' => 'Contract',         'loc' => '2760 - St Marys',       'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Interested in Sovereign',                  'fu' => '',                                                            'fct_offset' => 26],
            ['date' => '2026-04-27', 'name' => 'Thomas Olson',           'phone' => 'N/A',          'email' => 'thomasoslon57@gmail.com',          'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2573 - Tahmoor',        'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 22 Dulcimere St, Tahmoor',             'fu' => '',                                                            'fct_offset' => 5],
            ['date' => '2026-06-27', 'name' => 'Cynthia Pienaar',        'phone' => '0468 934 677', 'email' => 'cpienaar313@gmail.com',            'source' => 'Email',             'lead' => 'Google',            'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Emilio',  'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'H&L single storey $900-950k, 3-4 bed',    'fu' => '',                                                            'fct_offset' => 6],
            ['date' => '2026-07-27', 'name' => 'Sue Thomas',             'phone' => '0412 089 991', 'email' => 'sue.mtannan@bigpond.com',          'source' => 'Email',             'lead' => 'Facebook',          'type' => 'KDRB',             'loc' => '2567 - Eagle Vale',     'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'KDRB of Milano in Eagle Vale',             'fu' => '',                                                            'fct_offset' => 48],
            ['date' => '2026-08-27', 'name' => 'Emi Lou Bernardo-Yan',   'phone' => 'N/A',          'email' => 'elou_bernardo@yahoo.com',          'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2563 - Menangle Park',  'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 4063 Proposed Rd, Menangle Park',     'fu' => '',                                                            'fct_offset' => 36],
            ['date' => '2026-08-27', 'name' => 'Maureen Sahu-Khan',      'phone' => '0414 968 573', 'email' => 'msahukhan@gmail.com',              'source' => 'Email',             'lead' => 'Google',            'type' => 'KDRB/Dual Living', 'loc' => '2153 - Baulkham Hills', 'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Price for Cathy 26 as KDRB',               'fu' => '',                                                            'fct_offset' => 25],
            ['date' => '2026-08-27', 'name' => 'Susie Mudaliar',         'phone' => '0432 610 700', 'email' => 'susie-mudaliar1@hotmail.com',      'source' => 'Phone',             'lead' => 'Google',            'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Cheapest H&L packages in Austral',         'fu' => '',                                                            'fct_offset' => 3],
            ['date' => '2026-10-27', 'name' => 'Daniel Hodgson',         'phone' => '0422 421 246', 'email' => 'hodgson_dan@yahoo.com',            'source' => 'Email',             'lead' => 'Website',           'type' => 'KDRB',             'loc' => '2173 - Wattle Grove',   'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'KDRB of Sovereign on narrow lot',          'fu' => '',                                                            'fct_offset' => 2],
            ['date' => '2026-10-27', 'name' => 'Mominur Chowdhury',      'phone' => '0470 446 535', 'email' => 'toppach@gmail.com',                'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Michael', 'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 209 Hydrus St, Austral',               'fu' => '',                                                            'fct_offset' => 5],
            ['date' => '2026-09-27', 'name' => 'Ehren Vinuka',           'phone' => '0415 450 139', 'email' => 'ehrenchanukaperera@gmail.com',     'source' => 'Display Home',      'lead' => 'Display Home',      'type' => 'Contract',         'loc' => '2161 - Guildford',      'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => '12 Barret St; duplex subdivision',         'fu' => "09/05 - At Box Hill display.\n11/05 - Lot may comply CDC.", 'fct_offset' => 72],
            ['date' => '2026-11-27', 'name' => 'Sera Fotofili',          'phone' => '0432 675 970', 'email' => 'salome_sera@yahoo.com.au',         'source' => 'Phone',             'lead' => 'Signage',           'type' => 'KDRB',             'loc' => '2151 - North Rocks',    'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'KDRB on North Rocks Rd; budget $500-600k', 'fu' => '',                                                            'fct_offset' => 8],
            ['date' => '2026-11-27', 'name' => 'Joe Vella',              'phone' => '0412 388 077', 'email' => 'joeritavella@yahoo.com.au',        'source' => 'Phone',             'lead' => 'Signage',           'type' => 'Custom Duplex',    'loc' => '2148 - Blacktown',      'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Custom duplex in Blacktown',               'fu' => '',                                                            'fct_offset' => 6],
            ['date' => '2026-11-27', 'name' => 'Sharat Bahar',           'phone' => '0411 381 408', 'email' => 'ms_bahar@hotmail.com',             'source' => 'Phone',             'lead' => 'Facebook',          'type' => 'KDRB',             'loc' => '2770 - Mount Druitt',   'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'KDRB; double storey prices',               'fu' => '',                                                            'fct_offset' => 2],
            ['date' => '2026-12-27', 'name' => 'Danny Kau',              'phone' => 'N/A',          'email' => 'dcao007@gmail.com',                'source' => 'Email',             'lead' => 'N/A',               'type' => 'Duplex',           'loc' => '2166 - Canley Heights', 'rep' => 'Emilio',  'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Duplex on subdivided block',               'fu' => '',                                                            'fct_offset' => 29],
            ['date' => '2026-12-27', 'name' => 'James',                  'phone' => '0428 838 288', 'email' => 'N/A',                             'source' => 'Phone',             'lead' => 'Facebook',          'type' => 'Dual Living',      'loc' => 'N/A',                   'rep' => 'Michael', 'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Developer for dual occupancies',           'fu' => '12/05 - Forwarded to Michael',                               'fct_offset' => 12],
            ['date' => '2026-12-27', 'name' => 'Robert Michael',         'phone' => '02 9190 7550', 'email' => 'Robert@mightyhealth.com.au',       'source' => 'Email',             'lead' => 'N/A',               'type' => 'Dual Living',      'loc' => '2560 - Figtree Hill',   'rep' => 'Emilio',  'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Turnkey quotes; house & granny flat',       'fu' => '',                                                            'fct_offset' => 33],
            ['date' => '2026-05-13', 'name' => 'Rola Chamoun',           'phone' => '0414 502 055', 'email' => 'rolachamounpsych@gmail.com',       'source' => 'Email',             'lead' => 'Google',            'type' => 'Contract',         'loc' => '2190 - Greenacre',      'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Nice home design, 4 bedrooms',             'fu' => '14/05 - Asked Michael to follow up',                         'fct_offset' => 10],
            ['date' => '2026-05-13', 'name' => 'Mohit Ahuja',            'phone' => '0430 999 438', 'email' => 'mohitahuja65@gmail.com',           'source' => 'Email',             'lead' => 'Other',             'type' => 'Contract',         'loc' => '2145 - Wentworthville', 'rep' => 'Emilio',  'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Price of Sovereign',                       'fu' => '',                                                            'fct_offset' => 27],
            ['date' => '2026-05-14', 'name' => 'Rayson Liu',             'phone' => '0431 118 625', 'email' => 'liurayson@gmail.com',              'source' => 'Email',             'lead' => 'Friends',           'type' => 'H&L',              'loc' => '2563 - Menangle Park',  'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 2737 Rosehill Lane; first home',       'fu' => '',                                                            'fct_offset' => 7],
            ['date' => '2026-05-14', 'name' => 'Ankit Joshi',            'phone' => '0403 602 706', 'email' => 'ankitjoshi@hotmail.com',           'source' => 'Phone',             'lead' => 'Google',            'type' => 'KDRB',             'loc' => '2147 - Seven Hills',    'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Knockdown rebuild; single storey',          'fu' => '',                                                            'fct_offset' => 4],
            ['date' => '2026-05-15', 'name' => 'Prakash Pandey',         'phone' => '0452 652 028', 'email' => 'pr.14pandey@gmail.com',            'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Michael', 'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 209 Hydrus St',                        'fu' => '21/05 - Still shopping around',                              'fct_offset' => 9],
            ['date' => '2026-05-15', 'name' => 'Roman Rokka',            'phone' => '0450 869 026', 'email' => 'Girirajrokka89@gmail.com',         'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2563 - Menangle Park',  'rep' => 'Michael', 'status' => 'Lost',        'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Not genuine enquiry',                      'fu' => '21/05 - Same as Lot 12 Daisy St.',                           'fct_offset' => 20],
            ['date' => '2026-05-15', 'name' => 'Ryan Suares',            'phone' => '0412 939 705', 'email' => 'rsuares75@hotmail.com',            'source' => 'Phone',             'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2563 - Menangle Park',  'rep' => 'Michael', 'status' => '1st Deposit', 'dep1' => 'YES', 'dep2' => 'NO',  'notes' => 'Lot 2737 Rosehill Lane',                   'fu' => '21/05 - Paid deposit for Lot 2737 Rosehill Ln',             'fct_offset' => 14],
            ['date' => '2026-05-15', 'name' => 'Ahnad Khada',            'phone' => '0410 185 755', 'email' => 'ahnadkhada@gmail.com',             'source' => 'Phone',             'lead' => 'Referral',          'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Michael', 'status' => 'New',         'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'H&L packages in Austral',                  'fu' => '',                                                            'fct_offset' => 37],
            ['date' => '2026-05-15', 'name' => 'Yvette Mundell',         'phone' => '0408 531 207', 'email' => 'mundellyvette@gmail.com',          'source' => 'Phone',             'lead' => 'Signage',           'type' => 'H&L',              'loc' => '2572 - Thirlmere',      'rep' => 'Michael', 'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 812 Thirlmere Way',                    'fu' => '21/05 - May consider H&L',                                   'fct_offset' => 11],
            ['date' => '2026-05-17', 'name' => 'Albert Nghiem',          'phone' => 'N/A',          'email' => 'albert@carsforhope.com.au',        'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2563 - Menangle Park',  'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 2737 Rosehill Lane',                   'fu' => '19/05 - Package unavailable',                                'fct_offset' => 7],
            ['date' => '2026-05-17', 'name' => 'Bikram Khadka',          'phone' => '0426 121 992', 'email' => 'Bikramkhadka1234321@gmail.com',    'source' => 'Realestate.com',    'lead' => 'Realestate.com',    'type' => 'H&L',              'loc' => '2179 - Austral',        'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 209 Hydrus St',                        'fu' => '19/05 - Emailed info for Lot 209',                           'fct_offset' => 15],
            ['date' => '2026-05-17', 'name' => 'Mohammed Azhar Ali',     'phone' => '0426 168 277', 'email' => 'azharali.fj@gmail.com',            'source' => 'Email',             'lead' => 'Google',            'type' => 'Contract',         'loc' => '2560 - Campbelltown',   'rep' => 'Emilio',  'status' => 'Meeting',     'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Mediterranean; 312.5sqm',                  'fu' => '19/05 - Meeting Saturday 10am',                              'fct_offset' => 16],
            ['date' => '2026-05-19', 'name' => 'Nick Saengdara',         'phone' => '0421 833 856', 'email' => 'kadoomph@gmail.com',               'source' => 'Leppington Living', 'lead' => 'Leppington Living', 'type' => 'H&L',              'loc' => '2168 - Ashcroft',       'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Registered H&L packages',                  'fu' => '19/05 - Sent text with link',                                'fct_offset' => 13],
            ['date' => '2026-05-19', 'name' => 'Craig',                  'phone' => '0402 705 227', 'email' => 'N/A',                             'source' => 'Phone',             'lead' => 'N/A',               'type' => 'H&L',              'loc' => '2573 - Tahmoor',        'rep' => 'Michael', 'status' => 'Meeting',     'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Tahmoor lot; single storey',               'fu' => '19/05 - Meeting Sunday 10am',                                'fct_offset' => 18],
            ['date' => '2026-05-19', 'name' => 'Zazeh',                  'phone' => '0407 400 490', 'email' => 'zazeh@atotalapproach.com.au',      'source' => 'Phone',             'lead' => 'Signage',           'type' => 'H&L',              'loc' => '2572 - Thirlmere',      'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 812 Thirlmere Way',                    'fu' => '19/05 - Needs to sell first',                                'fct_offset' => 22],
            ['date' => '2026-05-20', 'name' => 'Ron Guardala',           'phone' => '0412 789 161', 'email' => 'ron.guardala@gmail.com',           'source' => 'Email',             'lead' => 'Other',             'type' => 'KDRB',             'loc' => '2210 - Peakhurst',      'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Pricing on Nice 36',                       'fu' => '21/05 - No reply; text sent',                                'fct_offset' => 31],
            ['date' => '2026-05-20', 'name' => 'Kenan Summersford',      'phone' => '0434 510 572', 'email' => 'kenan.summersford@gmail.com',      'source' => 'Email',             'lead' => 'Display Home',      'type' => 'KDRB',             'loc' => '2527 - Albion Park',    'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Mediterranean 30; budget cost',            'fu' => '20/05 - Emailed Medi 30 info',                               'fct_offset' => 19],
            ['date' => '2026-05-20', 'name' => 'Joseph Portelli',        'phone' => '0405 495 160', 'email' => 'josephp_12@hotmail.com',           'source' => 'Email',             'lead' => 'Display Home',      'type' => 'Contract',         'loc' => '2765 - Box Hill',       'rep' => 'Emilio',  'status' => 'Contacted',   'dep1' => 'NO',  'dep2' => 'NO',  'notes' => 'Lot 609 Mare St; retaining wall',          'fu' => "20/05 - Responded.\n21/05 - Waiting on sale contract",       'fct_offset' => 21],
        ];

        foreach ($rows as $row) {
            $offset = $row['fct_offset'];
            unset($row['fct_offset']);

            Enquiry::create(array_merge($row, [
                'first_contact_timestamp' => $now->copy()->subHours($offset),
                'files'                   => [],
            ]));
        }
    }
}
